"""
models/user.py — ORM model for the 'users' table.

Role in the system:
    Represents an authenticated user of the AgentWork platform. Every person
    who signs up gets one row in this table. The user record ties together
    identity (email + password hash), multi-tenancy (org_id), and account
    state (is_active).

    This is the central entity in the auth service. Tokens reference users,
    groups reference users via user_groups, and the JWT payload is built
    from user data at login time.

Columns:
    id         — UUID primary key, generated by Python (not the DB) so the
                 application knows the ID before the INSERT completes.
    email      — Globally unique across all organizations. Used as the JWT
                 subject ("sub") and the login identifier.
    password   — Argon2 hash produced by core/security.py. Never stored or
                 returned as plain text anywhere.
    org_id     — Foreign key to organizations.id. Nullable because legacy
                 users (created before Phase 2 signup flow) may not have an
                 org yet. Will be non-nullable once all users go through the
                 org-creation signup flow.
    is_active  — Soft disable flag. Setting this to False blocks login without
                 deleting the user record or invalidating their history.
    created_at — Audit timestamp. Set once at INSERT, never updated.

Design decisions:
    - No 'role' column. Roles are replaced by groups (user_groups table) which
      support many-to-many assignment and org-scoped names.
    - No 'name' or 'display_name' column at this stage. User profile data
      (names, avatars, preferences) belongs in the user-service, not auth.

Dependencies:
    - app.db.base.Base           →  SQLAlchemy declarative base
    - organizations table        →  FK constraint on org_id
    - Used by: app.services.auth_service, app.models.token, app.models.user_group
"""

from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
import uuid
from datetime import datetime
from app.db.base import Base


class User(Base):
    __tablename__ = "users"

    id         = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email      = Column(String(255), unique=True, index=True, nullable=False)
    password   = Column(String(255), nullable=False)
    org_id     = Column(UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=True)
    is_active  = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
